### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by grandtiger** [irustm/angular-nodegui#5]
I am very excited to find this project. However, I got the following error when trying to run it. Any idea what is causing this?

I am using Windows 10 with Node v12.13.1, Visual Studio 2019, and cmake v3.16.2.

```
PS D:\temp\angular-nodegui> npm start

> angular-nodegui@0.0.0 start D:\temp\angular-nodegui
> npm run build-dev && qode ./dist/src/main.js


> angular-nodegui@0.0.0 build-dev D:\temp\angular-nodegui
> ngc -p tsconfig.app.json

node_modules/@nodegui/nodegui/dist/lib/QtWidgets/QMainWindow.d.ts(162,9): error TS1086: An accessor cannot be declared in an ambient context.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-nodegui@0.0.0 build-dev: `ngc -p tsconfig.app.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-nodegui@0.0.0 build-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Foo\AppData\Roaming\npm-cache\_logs\2019-12-25T02_08_52_041Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-nodegui@0.0.0 start: `npm run build-dev && qode ./dist/src/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-nodegui@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Foo\AppData\Roaming\npm-cache\_logs\2019-12-25T02_08_52_130Z-debug.log
PS D:\temp\angular-nodegui> 
```

**Comment by irustm** [comment]
Please try

Delete your package-lock.json file and node_modules folder. Then do `npm cache clean`

```npm cache clean --force```
do `npm install`

again and run

If this doesn't work out for you, show me what's in the logs.

**Comment by grandtiger** [comment]
@irustm Thanks for your help! I tried your suggestion, but got the same exact error. Following is all the content in the log file. BTW, this is done from another PC from scratch. Unfortunately the error is exactly the same. Did I miss anything obvious? Thanks again!

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Foo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-nodegui@0.0.0~prestart: angular-nodegui@0.0.0
6 info lifecycle angular-nodegui@0.0.0~start: angular-nodegui@0.0.0
7 verbose lifecycle angular-nodegui@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle angular-nodegui@0.0.0~start: PATH: C:\Users\Foo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\GitHub\angular-nodegui\node_modules\.bin;C:\Users\Foo\AppData\Local\Continuum\miniconda3\condabin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Amazon Corretto\jdk1.8.0_232\bin;C:\Program Files (x86)\Amazon Corretto\jdk1.8.0_232\bin;C:\Program Files (x86)\Amazon Corretto\jdk1.8.0_212\bin;C:\Anaconda3;C:\Anaconda3\Library\mingw-w64\bin;C:\Anaconda3\Library\usr\bin;C:\Anaconda3\Library\bin;C:\Anaconda3\Scripts;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;Y:\program\pb4dknti;Y:\program\bin;c:\Rtools\bin;C:\Rtools\mingw_64\bin;c:\Rtools\mingw_32\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;c:\tools;Y:\PROD\SRC\LIB;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Amazon Corretto\jdk1.8.0_232\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\dotnet\;C:\Program Files\PuTTY\;C:\Program Files\PowerShell\6\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Foo\AppData\Roaming\TinyTeX\bin\win32;C:\Users\Foo\AppData\Local\Continuum\miniconda3;C:\Users\Foo\AppData\Local\Continuum\miniconda3\Library\mingw-w64\bin;C:\Users\Foo\AppData\Local\Continuum\miniconda3\Library\usr\bin;C:\Users\Foo\AppData\Local\Continuum\miniconda3\Library\bin;C:\Users\Foo\AppData\Local\Continuum\miniconda3\Scripts;c:\q\w32;C:\Users\Foo\AppData\Local\Programs\Python\Launcher\;C:\tools\pandoc-2.2.1;C:\Users\Foo\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\;C:\Users\Foo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\Foo\.dotnet\tools;C:\Program Files\Amazon Corretto\jdk1.8.0_222\bin;C:\Users\Foo\AppData\Local\Microsoft\WindowsApps;C:\R\R-3.5.1\bin;C:\Users\Foo\AppData\Local\Julia-1.1.0\bin;C:\Users\Foo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;C:\tools\swigwin-3.0.12;c:\q\w32;D:\Trade\bin;D:\Tools;C:\Program Files\CMake\bin;C:\Users\Foo\AppData\Roaming\npm
9 verbose lifecycle angular-nodegui@0.0.0~start: CWD: D:\GitHub\angular-nodegui
10 silly lifecycle angular-nodegui@0.0.0~start: Args: [ '/d /s /c', 'npm run build-dev && qode ./dist/src/main.js' ]
11 silly lifecycle angular-nodegui@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle angular-nodegui@0.0.0~start: Failed to exec start script
13 verbose stack Error: angular-nodegui@0.0.0 start: `npm run build-dev && qode ./dist/src/main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Foo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Foo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid angular-nodegui@0.0.0
15 verbose cwd D:\GitHub\angular-nodegui
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Foo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.14.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error angular-nodegui@0.0.0 start: `npm run build-dev && qode ./dist/src/main.js`
22 error Exit status 1
23 error Failed at the angular-nodegui@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by irustm** [comment]
I founded solve, 

https://github.com/microsoft/TypeScript/issues/33939

You must remove this line in node_modules/@nodegui/nodegui/dist/lib/QtWidgets/QMainWindow.d.ts(162,9)

```
 get layout(): NodeLayout | undefined;
```
and then try `npm run start`

**Comment by grandtiger** [comment]
@irustm thank you so much! it works with this trick.

**Comment by setrar** [comment]
```
node_modules/@nodegui/nodegui/dist/lib/QtWidgets/QMainWindow.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context.
```

> I have found a solution
> 
> [microsoft/TypeScript#33939](https://github.com/microsoft/TypeScript/issues/33939)
> 
> You must remove this line in node_modules/@nodegui/nodegui/dist/lib/QtWidgets/QMainWindow.d.ts(162,9)
> 
> ```
>  get layout(): NodeLayout | undefined;
> ```
> 
> and then try `npm run start`

Same trick on macOS Big Sur ver 11.0.1

removed the line `get layout(): NodeLayout<any> | undefined;`

```
node_modules/@nodegui/nodegui/dist/lib/QtWidgets/QMainWindow.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context.
```
